from manifold import Manifold


def test_example_get_split_count():
    data = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""
    manifold = Manifold(data)
    expected = 21
    assert manifold.get_split_count() == expected


def test_example_as_graph_count_possible_journeys():
    data = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""
    manifold = Manifold(data)
    expected = 40
    assert manifold.as_graph().count_possible_journeys() == expected
